var user = {
    "login": "locomotes",
    "id": 5142640,
    "avatar_url": "https://avatars.githubusercontent.com/u/5142640?",
    "gravatar_id": "39edf215953d554361d15735bac454a7",
    "url": "https://api.github.com/users/locomotes",
    "html_url": "https://github.com/locomotes",
    "followers_url": "https://api.github.com/users/locomotes/followers",
    "following_url": "https://api.github.com/users/locomotes/following{/other_user}",
    "gists_url": "https://api.github.com/users/locomotes/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/locomotes/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/locomotes/subscriptions",
    "organizations_url": "https://api.github.com/users/locomotes/orgs",
    "repos_url": "https://api.github.com/users/locomotes/repos",
    "events_url": "https://api.github.com/users/locomotes/events{/privacy}",
    "received_events_url": "https://api.github.com/users/locomotes/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Jonathan Dickerson",
    "company": "",
    "blog": "",
    "location": "",
    "email": "",
    "hireable": false,
    "bio": null,
    "public_repos": 11,
    "public_gists": 0,
    "followers": 3,
    "following": 5,
    "created_at": "2013-08-01T23:24:30Z",
    "updated_at": "2014-06-18T16:55:25Z"
};